-- MySQL Script generated by MySQL Workbench
-- Thu Jan 15 14:47:16 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`roles` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`roles` (
  `RID` INT NOT NULL AUTO_INCREMENT,
  `RoleName` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`RID`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `RID_UNIQUE` ON `mydb`.`roles` (`RID` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`payment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`payment` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`payment` (
  `PID` INT NOT NULL AUTO_INCREMENT,
  `token` INT NOT NULL,
  PRIMARY KEY (`PID`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `PID_UNIQUE` ON `mydb`.`payment` (`PID` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`address`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`address` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`address` (
  `AID` INT NOT NULL,
  `street_name` VARCHAR(45) NOT NULL,
  `unit_number` VARCHAR(10) NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  `country` VARCHAR(45) NOT NULL,
  `ZIP_code` INT NOT NULL,
  PRIMARY KEY (`AID`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `AID_UNIQUE` ON `mydb`.`address` (`AID` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`user` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `UID` VARCHAR(36) NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `role_ID` INT NOT NULL,
  `payment_ID` INT NULL,
  `address_ID` INT NULL,
  `email` VARCHAR(100) NOT NULL,
  `password_hash` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`UID`),
  CONSTRAINT `Role`
    FOREIGN KEY (`role_ID`)
    REFERENCES `mydb`.`roles` (`RID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Payment`
    FOREIGN KEY (`payment_ID`)
    REFERENCES `mydb`.`payment` (`PID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Address`
    FOREIGN KEY (`address_ID`)
    REFERENCES `mydb`.`address` (`AID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `Role_idx` ON `mydb`.`user` (`role_ID` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `Payment_idx` ON `mydb`.`user` (`payment_ID` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `Address_idx` ON `mydb`.`user` (`address_ID` ASC) VISIBLE;

SHOW WARNINGS;
CREATE UNIQUE INDEX `UID_UNIQUE` ON `mydb`.`user` (`UID` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`order_stat`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`order_stat` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`order_stat` (
  `OSID` INT NOT NULL AUTO_INCREMENT,
  `order_status` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`OSID`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `OSID_UNIQUE` ON `mydb`.`order_stat` (`OSID` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`colour`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`colour` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`colour` (
  `CID` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `image` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`CID`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `CID_UNIQUE` ON `mydb`.`colour` (`CID` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`size`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`size` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`size` (
  `SID` INT NOT NULL AUTO_INCREMENT,
  `size` VARCHAR(45) NOT NULL,
  `size_price_multi` DECIMAL(1) NOT NULL,
  PRIMARY KEY (`SID`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `SID_UNIQUE` ON `mydb`.`size` (`SID` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`item`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`item` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`item` (
  `IID` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `price` DECIMAL(2) NOT NULL,
  `description` VARCHAR(100) NULL,
  `availablity` BINARY(1) NULL,
  PRIMARY KEY (`IID`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `IID_UNIQUE` ON `mydb`.`item` (`IID` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`order`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`order` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`order` (
  `OID` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `order_status_id` INT NOT NULL,
  `item_id` INT NOT NULL,
  `colour_id` INT NOT NULL,
  `size_id` INT NOT NULL,
  `payment_id` INT NOT NULL,
  `address_id` INT NOT NULL,
  `item_qty` INT NOT NULL,
  `order_time` TIMESTAMP(3) NOT NULL,
  `order_hash` VARCHAR(45) NOT NULL,
  `order_price` DECIMAL(2) NOT NULL,
  PRIMARY KEY (`OID`),
  CONSTRAINT `user`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user` (`UID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `order_stat`
    FOREIGN KEY (`order_status_id`)
    REFERENCES `mydb`.`order_stat` (`OSID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `colour`
    FOREIGN KEY (`colour_id`)
    REFERENCES `mydb`.`colour` (`CID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `size`
    FOREIGN KEY (`size_id`)
    REFERENCES `mydb`.`size` (`SID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `item`
    FOREIGN KEY (`item_id`)
    REFERENCES `mydb`.`item` (`IID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `payment`
    FOREIGN KEY (`payment_id`)
    REFERENCES `mydb`.`payment` (`PID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `address`
    FOREIGN KEY (`address_id`)
    REFERENCES `mydb`.`address` (`AID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `OID_UNIQUE` ON `mydb`.`order` (`OID` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `user_idx` ON `mydb`.`order` (`user_id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `order_stat_idx` ON `mydb`.`order` (`order_status_id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `colour_idx` ON `mydb`.`order` (`colour_id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `size_idx` ON `mydb`.`order` (`size_id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `item_idx` ON `mydb`.`order` (`item_id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `payment_idx` ON `mydb`.`order` (`payment_id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `address_idx` ON `mydb`.`order` (`address_id` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`item_audit_logging`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`item_audit_logging` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`item_audit_logging` (
  `item_audit_id` INT NOT NULL AUTO_INCREMENT,
  `item_id` INT NOT NULL,
  `action` VARCHAR(45) NOT NULL,
  `actor_id` VARCHAR(36) NOT NULL,
  `previous_values` JSON NOT NULL,
  `new_values` JSON NOT NULL,
  `timestamp` TIMESTAMP(2) NOT NULL,
  PRIMARY KEY (`item_audit_id`),
  CONSTRAINT `item_id`
    FOREIGN KEY (`item_id`)
    REFERENCES `mydb`.`item` (`IID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `actor_id`
    FOREIGN KEY (`actor_id`)
    REFERENCES `mydb`.`user` (`UID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `IID_UNIQUE` ON `mydb`.`item_audit_logging` (`item_audit_id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `item_id_idx` ON `mydb`.`item_audit_logging` (`item_id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `actor_id_idx` ON `mydb`.`item_audit_logging` (`actor_id` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`user_audit_logging`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`user_audit_logging` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`user_audit_logging` (
  `user_audit_id` INT NOT NULL AUTO_INCREMENT,
  `user_id` VARCHAR(36) NOT NULL,
  `action` VARCHAR(45) NOT NULL,
  `actor_id` VARCHAR(36) NOT NULL,
  `previous_values` JSON NOT NULL,
  `new_values` JSON NOT NULL,
  `timestamp` TIMESTAMP(2) NOT NULL,
  PRIMARY KEY (`user_audit_id`),
  CONSTRAINT `user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user` (`UID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `actor_id`
    FOREIGN KEY (`actor_id`)
    REFERENCES `mydb`.`user` (`UID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `IID_UNIQUE` ON `mydb`.`user_audit_logging` (`user_audit_id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `actor_id_idx` ON `mydb`.`user_audit_logging` (`actor_id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `user_id_idx` ON `mydb`.`user_audit_logging` (`user_id` ASC) VISIBLE;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
